username: str = "hugofyptest@gmail.com"
password: str = "FYP4400test"
defined_category_list: list[list[str]] = []
text_list = []
url_list = []
full_url_list = []
Label_Category_dict = {"Label": [],  "Category": []}
Keywords_Exist_dict = {"Keyword": ["T&C", "P.I.C.S", "Opt-in/Opt-out"], "Exist?": ["No", "No", "No"]}
scraped_text_list = []
scraped_link_text = []
all_Label_Category_dict = []
all_Keywords_Exist_dict = []
all_Label_Category_dict_list = []
all_Keywords_Exist_dict_list = []
full_url_list_list = []